# Generated by Django 5.2.7 on 2025-10-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_password_change',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
    ]
